### ISSUE TITLE
Peer-To-Peer review -03/12-2019

### ISSUE THREAD

**Issue by CornetS28** [dev1980/facebook-clone#3]
Issues found:
- Basically and so far, there is no issue that could attract our attention as you are on your third milestone, which only requires "device" that takes care of the user sign-up, login, and logout and the post feature which we (team-35-the-deadpools) think you have done a very good job by writing concise, clear, and clean  #codes.

keep up the good work Miguel!

**Comment by mapra99** [comment]
Thanks @CornetS28 , and thanks Team for the review
